# Generated by Django 5.2.3 on 2025-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('gravidez', models.BooleanField(default=False)),
                ('peso', models.FloatField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
