version: "3.9"

services:
  db:
    image: postgres:15
    container_name: BANCO
    restart: always
    environment:
        POSTGRES_USER: user 
        POSTGRES_PASSWORD: password
        POSTGRES_DB: diario_ciclos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: WEB
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./app
    ports:
    - "8000:8000"
    depends_on:
    - db




  test:
    container_name: TESTES
    build: .
    command: pytest
    

volumes:
  postgres_data:
