version: "1.0"
services:
  - name: diario-ciclos-backend
    type: web
    image: python:3.12-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - port: 8000
        protocol: http
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    healthCheck:
      path: /api/health/
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      cpu: 0.5
      memory: 512Mi
    scaling:
      min: 1
      max: 3 