# Generated by Django 5.2.1 on 2025-07-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('intensidade', models.CharField(
                    choices=[
                        ('LEVE', 'Leve'),
                        ('MODERADO', 'Moderado'),
                        ('INTENSO', 'Intenso'),
                        ('MUITO_INTENSO', 'Muito Intenso')
                    ],
                    max_length=15
                )),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_sintoma', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('pratica', models.BooleanField(default=False)),
                ('remedio_tomado', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True
                )),
                ('ciclo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fisicos',
                    to='ciclos.ciclo'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('intensidade', models.CharField(
                    choices=[
                        ('LEVE', 'Leve'),
                        ('MODERADO', 'Moderado'),
                        ('INTENSO', 'Intenso'),
                        ('MUITO_INTENSO', 'Muito Intenso')
                    ],
                    max_length=15
                )),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_sintoma', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('gatilho', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True
                )),
                ('humor', models.CharField(
                    choices=[
                        ('FELICIDADE', 'Felicidade'),
                        ('TRISTEZA', 'Tristeza'),
                        ('IRRITACAO', 'Irritação'),
                        ('ANSIEDADE', 'Ansiedade')
                    ],
                    max_length=15
                )),
                ('ciclo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='humores',
                    to='ciclos.ciclo'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libido',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('intensidade', models.CharField(
                    choices=[
                        ('LEVE', 'Leve'),
                        ('MODERADO', 'Moderado'),
                        ('INTENSO', 'Intenso'),
                        ('MUITO_INTENSO', 'Muito Intenso')
                    ],
                    max_length=15
                )),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_sintoma', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('relacoes_com_parceiro', models.BooleanField(default=False)),
                ('relacoes_sem_parceiro', models.BooleanField(default=False)),
                ('ciclo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='libidos',
                    to='ciclos.ciclo'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secrecao',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('intensidade', models.CharField(
                    choices=[
                        ('LEVE', 'Leve'),
                        ('MODERADO', 'Moderado'),
                        ('INTENSO', 'Intenso'),
                        ('MUITO_INTENSO', 'Muito Intenso')
                    ],
                    max_length=15
                )),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_sintoma', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('textura', models.CharField(
                    choices=[
                        ('AQUOSA', 'Aquosa'),
                        ('CREMOSA', 'Cremosa'),
                        ('ELASTICA', 'Elástica'),
                        ('PEGAJOSA', 'Pegajosa')
                    ],
                    max_length=15
                )),
                ('remedio_tomado', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True
                )),
                ('ciclo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='secrecoes',
                    to='ciclos.ciclo'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
